### ISSUE TITLE
Unable to perform MME export from NMR database due to complex/non-traditional textblocks

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/Nightmare-Redux#4]
GitHub REFUSES my zip files, so I had to upload it to some random free site, but it seems legit:

`link edited out`

To replicate error with attached database file:

Tools > Database > Export to MMud Explorer
Click Export to MME
Popup error:
"Error 380: ProgCtrl
Invalid property value"

To create MME Export without error, Delete textblocks 5568-5881.  Repeat steps above.  Exports with no issues.

------------------------------  See below for my own guess as to what might be happening

I hypothesize that one of two unconventional things I did are causing this problem.  

Firstly, some of my textblocks use "addability x -1" to subtract from player abilities.

Secondly, and more likely, I created a Quest Advisor NPC which launches a VERY long textblock that adds a temporary player ability as a variable to be utilized as a counter (since textblocks normally will only execute one line and then terminate).  It then increments this ability and casts a spell to launch another thread of the same textblock, but each line of the textblock checks a separate quest flag and returns relevant text to indicate where you are on your quests or what you have completed.  I believe this may be the issue because NMR may be trying to create the pop-up in MME where you can see the chain of textblock commands, except that since every line of the textblock casts a spell that re-launches the textblock, and MME isn't a player and therefore doesn't actually have abilities to use as a counter, i suspect your program may be interpreting this as an infinite loop and bombing out.

**Comment by syntax53** [comment]
The error doesn't say something like "Error ##: IN SOMETHING? " ??

e.g. "Error " & Err.Number & " in [" & sSource & "]:"

**Comment by syntax53** [comment]
Believe it or not I believe your issue was just that you had crossed a magical number of records when calculating the progress bar range which then fell into some bad code I wrote.  Deleting the textblocks just reduced the record numbers enough :P

Just to clarify, the error happened almost immediately after clicking go, right?

**Comment by CuckooRules** [comment]
Yes, the error occurs almost immediately and the text of the error in its entirety is what I put in quotes in my original message.

**Comment by syntax53** [comment]
Yup, all makes sense.  Fixed for next release.
