### ISSUE TITLE
Feature Request: Find/Goto last room on map

### ISSUE THREAD

**Issue by BearFather** [syntax53/Nightmare-Redux#5]
The last button in the room editor did the last room on that map. Instead of all the maps.

**Comment by syntax53** [comment]
Think you have a typo there.  I assume you are asking for a feature that pulls the last room number for the current map?

**Comment by BearFather** [comment]
Yes your correct, I'm a dumbass

**Comment by syntax53** [comment]
I can do that, but it won't be fast. There is no way to find the last room without scanning the entire database.

**Comment by BearFather** [comment]
Couldn't you do it at run time, Ok I really don't have the DB is laid out.  My thought is when you load that map in the room editor you could just scan that map.  But i can see how it could add a load on it.

**Comment by BearFather** [comment]
How about an open in tools to scan for the last number in all or a certain map.

**Comment by syntax53** [comment]
There is no way to scan a map.  There is call next, previous, and get specific map/room.  And you may also notice that it indexes them by room number.  e.g. If you start at map 1 room 1 and keep clicking next, you'll see it goes through all of the map room 1's and then room 2's, etc.  What would be a little faster, with that in mind, is to start at the end and go in reverse until it finds a room with the specified map.

**Comment by BearFather** [comment]
Ahh I did not is how that worked. with maps. That will be handy. Thanks.

**Comment by syntax53** [comment]
completed for next release
